# File: app.py
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from pydantic import BaseModel
import os
import time
from Pipeline import run_full_pipeline

# 1. Setup FastAPI
app = FastAPI(
    title="Real Estate Data Pipeline API",
    description="A service to scrape, analyze, and plot real estate data based on an input area."
)


# 2. Define Request Body Model
class AreaRequest(BaseModel):
    area: str = "tempe"  # Default example area


# 3. Define the directory to store/retrieve generated files
# This assumes the app is run from the same directory as the other Python files
FILE_DIRECTORY = os.path.dirname(os.path.abspath(__file__))


# 4. API Endpoint: Run the Pipeline
@app.post("/run-pipeline/")
async def start_pipeline(request: AreaRequest, background_tasks: BackgroundTasks):
    """
    Triggers the full data pipeline (Scrape -> Analyze -> Plot) for the specified area.
    The task is run in the background as scraping can be slow.
    """
    area_name = request.area.lower().strip()

    if not area_name:
        raise HTTPException(status_code=400, detail="Area name cannot be empty.")

    # Run the pipeline in the background to avoid blocking the API worker
    background_tasks.add_task(run_full_pipeline, area_name)

    return {
        "status": "processing",
        "area": area_name,
        "message": f"Pipeline started for area '{area_name}'. Check back later for the results using the expected plot URL."
    }


# 5. API Endpoint: Retrieve the Plot Image
@app.get("/plots/{plot_filename}")
async def get_plot_image(plot_filename: str):
    """
    Retrieves the generated JPEG plot file.
    Example filename format: price_analysis_tempe.jpeg
    """
    # Ensure only valid plot files are served
    if not plot_filename.startswith("price_analysis_") or not plot_filename.endswith(".jpeg"):
        raise HTTPException(status_code=400, detail="Invalid plot filename format.")

    file_path = os.path.join(FILE_DIRECTORY, plot_filename)

    # Wait up to 30 seconds for the file to be generated by the background task
    wait_time = 0
    while not os.path.exists(file_path) and wait_time < 30:
        time.sleep(1)
        wait_time += 1

    if not os.path.exists(file_path):
        raise HTTPException(status_code=404,
                            detail=f"Plot file '{plot_filename}' not found. The pipeline might still be running or have failed. Try again later.")

    return FileResponse(file_path, media_type="image/jpeg", filename=plot_filename)


# 6. Instructions for Running the Application
"""
To run this application:

1.  **Save the files:** Ensure `app.py`, `pipeline.py`, `Spider.py`, `Analyze.py`, and `Plot.py` are all in the same directory.
2.  **Install dependencies:**
    pip install fastapi uvicorn pandas scrapy matplotlib
3.  **Start the server:**
    uvicorn app:app --reload

The API will be available at http://127.0.0.1:8000.

**To trigger the pipeline:**
Send a POST request to: http://127.0.0.1:8000/run-pipeline/
Body (JSON): {"area": "tempe"}

**To retrieve the plot (e.g., after the task is finished):**
Send a GET request to: http://127.0.0.1:8000/plots/price_analysis_tempe.jpeg
"""