import json
from collections import Counter
import os
import re

# 1. Configuration
# Replace 'maricopa.json' with the actual filename generated by your Spider.py
JSON_FILE_NAME = "globe.json"


def clean_and_convert_to_float(value):
    if value is None:
        return None

    s = str(value).strip()

    # Priority 1: Handle fractions (e.g., "1/2")
    if '/' in s:
        parts = s.split('/')
        if len(parts) == 2:
            try:
                # Attempt to convert parts to float and divide
                numerator = float(parts[0].strip())
                denominator = float(parts[1].strip())
                if denominator != 0:
                    return numerator / denominator
            except ValueError:
                # If conversion fails (e.g., "N/A"), fall through to next logic
                pass

    # Priority 2: Handle standard numbers (e.g., "$1,200,000", "4.5", "5")
    # This handles numbers with currency symbols, commas, or unit text.
    try:
        # Remove common non-numeric characters like $, ,, spaces, and units (sq ft)
        # Note: We must exclude / here, which is handled above.
        cleaned_value = re.sub(r'[^\d.]', '', s)
        if cleaned_value:
            return float(cleaned_value)
    except ValueError:
        return None

    return None


def analyze_real_estate_data(file_name):
    """
    Reads the JSON file, calculates averages, and finds the most frequent agency.
    """
    if not os.path.exists(file_name):
        print(f"Error: JSON file '{file_name}' not found.")
        print("Please make sure you have run your 'Spider.py' script to generate the output file.")
        return

    try:
        with open(file_name, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{file_name}'. Check if the file is valid.")
        return
    except Exception as e:
        print(f"An unexpected error occurred while reading the file: {e}")
        return

    # Initialize lists to store numeric data for calculations
    prices = []
    beds = []
    baths = []
    sq_fts = []
    agencies = []

    # Track the total number of valid listings to ensure we divide by the correct number
    valid_listings_count = 0

    for listing in data:
        # Check for essential 'price' field to consider it a valid listing for analysis
        if 'price' in listing and listing['price']:
            valid_listings_count += 1

            # 1. Price
            price_val = clean_and_convert_to_float(listing.get('price'))
            if price_val is not None:
                prices.append(price_val)

            # 2. Beds
            beds_val = clean_and_convert_to_float(listing.get('beds'))
            if beds_val is not None:
                beds.append(beds_val)

            # 3. Baths
            baths_val = clean_and_convert_to_float(listing.get('baths'))
            if baths_val is not None:
                baths.append(baths_val)

            # 4. Sq. Ft.
            sq_ft_val = clean_and_convert_to_float(listing.get('sq_ft'))
            if sq_ft_val is not None:
                sq_fts.append(sq_ft_val)

            # 5. Agency
            agency_name = listing.get('agency')
            if agency_name:
                agencies.append(agency_name)

    if not valid_listings_count:
        print("No valid listings found in the JSON file for analysis.")
        return

    print("-" * 50)
    print(f"Real Estate Data Analysis for {valid_listings_count} Listings")
    print("-" * 50)

    # Calculate and print Averages

    # Average Price
    avg_price = sum(prices) / len(prices) if prices else 0
    print(f"Average Price of Listings: ${avg_price:,.2f}")

    # Average Beds (Rounded and cast to integer as requested)
    avg_beds_float = sum(beds) / len(beds) if beds else 0
    avg_beds_int = int(round(avg_beds_float))
    print(f"Average Bedrooms: {avg_beds_int}")

    # Average Baths (Remains a float to show half-bath precision as requested)
    avg_baths = sum(baths) / len(baths) if baths else 0
    print(f"Average Bathrooms: {avg_baths:.2f}")

    # Average Sq. Ft.
    avg_sqft = sum(sq_fts) / len(sq_fts) if sq_fts else 0
    print(f"Average Square Footage: {avg_sqft:,.2f} sq ft")

    print("-" * 50)

    # Find Real Estate Agency with Most Listings
    if agencies:
        # Counter counts the frequency of each item in the list
        agency_counts = Counter(agencies)
        # most_common(1) returns a list of the single most common item and its count: [('Agency Name', 123)]
        most_common_agency, count = agency_counts.most_common(1)[0]

        print(f"Real Estate Agency with Most Listings:")
        print(f"  Agency: {most_common_agency}")
        print(f"  Listings: {count} (out of {len(agencies)})")
    else:
        print("Could not determine the most frequent agency (agency data missing or empty).")

    print("-" * 50)


# Run the analysis
if __name__ == "__main__":
    analyze_real_estate_data(JSON_FILE_NAME)
